### PR TITLE
PSCustomObject related traps

### PR DESCRIPTION
**Pull request by KevinMarquette**
Added a few items around PSCustomObject

### CODE REVIEW

**Comment by nightroman** [comment]
@KevinMarquette 
Thank you for these good additional cases. If you do not mind I will tweak the style of code samples, for consistency with other samples.

I am not sure about the sample with `If( -Not [string]::isNullOrEmpty($object) )`. While the trap "empty ToString()" is legit, the sample represents some not commonly used and perhaps questionable technique. I will think of it.

**Comment by nightroman** [comment]
```
+Third, the `PSCustomObject` or `PSObject` object types are an exception to this 
 +rule. A collection of these objects will have a correct count, but a single 
 +object will return `$null` for `.count`.
```

I cannot see this issue for `PSObject`, not with the provided sample at least. Can you explain?

**Comment by KevinMarquette** [comment]
No problem, make whatever changes you think are needed. I have just ran into these with other people and just noticed they were not listed here. 

I could be incorrect on the `PSObject` then. I recall them having the same issue, but I didn't test it. I could just be mistaken on that one.

**Comment by nightroman** [comment]
I have made some tweaks and added tests, too.
Thank you once again. These are really useful cases and I was not aware of them.

**Pull request merged**
